apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend-deploy
  namespace: istio-demo
spec:
  selector:
    matchLabels:
      app: nginx-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: frontend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
